In [1]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
s = pd.Series([10,20,30], index = ['p','q','r'])
s

p    10
q    20
r    30
dtype: int64

In [7]:
s = pd.Series({'x':5,'y':10,'z':15})
s

x     5
y    10
z    15
dtype: int64

In [8]:
s['y']

np.int64(10)

In [11]:
data = {"Name":['Rahul','Priya','Amit','Neha'],
        "Age":[22,21,23,22],
        "City":['Pune','Mumbai','NAshik','Delhi']}
df = pd.DataFrame(data)
df

    Name  Age    City
0  Rahul   22    Pune
1  Priya   21  Mumbai
2   Amit   23  NAshik
3   Neha   22   Delhi

In [14]:
data = [['Rahul',22,'Pune'],
        ['Priya',21,'Mumbai'],
        ['Amit',23,'Nashik'],
        ['Neha',22,'Delhi']]
df = pd.DataFrame(data,columns=['Name','Age','City'])
print(df)

    Name  Age    City
0  Rahul   22    Pune
1  Priya   21  Mumbai
2   Amit   23  Nashik
3   Neha   22   Delhi

In [15]:
df['Name']

0    Rahul
1    Priya
2     Amit
3     Neha
Name: Name, dtype: str

In [17]:
df[['Name','City']]

    Name    City
0  Rahul    Pune
1  Priya  Mumbai
2   Amit  Nashik
3   Neha   Delhi

In [19]:
df.loc[0:1]

    Name  Age    City
0  Rahul   22    Pune
1  Priya   21  Mumbai

In [23]:
df.iloc[2]

Name      Amit
Age         23
City    Nashik
Name: 2, dtype: object

In [24]:
df['Marks'] = [78,85,90,67]
df

    Name  Age    City  Marks
0  Rahul   22    Pune     78
1  Priya   21  Mumbai     85
2   Amit   23  Nashik     90
3   Neha   22   Delhi     67

In [25]:
df['Course'] = ['Python','Java','Python','Data Science']
df

    Name  Age    City  Marks        Course
0  Rahul   22    Pune     78        Python
1  Priya   21  Mumbai     85          Java
2   Amit   23  Nashik     90        Python
3   Neha   22   Delhi     67  Data Science

In [27]:
df.drop("City",axis=1)

    Name  Age  Marks        Course
0  Rahul   22     78        Python
1  Priya   21     85          Java
2   Amit   23     90        Python
3   Neha   22     67  Data Science

In [29]:
df.drop(1)

    Name  Age    City  Marks        Course
0  Rahul   22    Pune     78        Python
2   Amit   23  Nashik     90        Python
3   Neha   22   Delhi     67  Data Science

In [33]:
(df[df['Age'] > 22])

   Name  Age    City  Marks  Course
2  Amit   23  Nashik     90  Python

In [35]:
(df[df['City'] == 'Pune'])

    Name  Age  City  Marks  Course
0  Rahul   22  Pune     78  Python

In [41]:
(df[(df['Age'] > 21)&(df['City'] == 'Pune')])

    Name  Age  City  Marks  Course
0  Rahul   22  Pune     78  Python

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("pandas.csv")
print(df.head(3))

                      Name   Age  Maths  Science  English  Computer  \
0          Avani Chaudhari  32.0     85       88     82.0      90.0
1  Shravani Goraksha Sukre  34.0     78       80     75.0      82.0
2      Prerana Sachin Veer  31.0     92       89     90.0      95.0

   Percentage
0       86.25
1       78.75
2         NaN

In [7]:
df = pd.read_csv("pandas.csv")
print(df.columns)

Index(['Name', 'Age', 'Maths', 'Science', 'English', 'Computer', 'Percentage'], dtype='str')

In [19]:
df = pd.read_csv("pandas.csv")
print(df[['Name', 'Marks']])

                         Name  Marks
0             Avani Chaudhari     99
1     Shravani Goraksha Sukre     99
2         Prerana Sachin Veer     99
3        Shreya Tanaji Jadhav     52
4          Ashwin Nitin Dhake     30
5       Anushka Nilesh Jadhav     12
6           Sarthak Darandale     95
7           Riya Vijay Sawant     55
8         Pradnya Pramod Ghag     12
9   Samruddhi Vinod Talagatti     32
10        Srushti Anand Dhoka     23
11          Pooja Vijay Lakhe     62
12     Sailee Pandit Hingmire      1
13  Yashshri Prashant Tembare     21
14     Shravani Rajesh Jadhav      1
15            Tanishka Gawade     16
16     Leena Ramesh Ghumatkar     62
17        Archita Ankur Dhoka     51
18  Samruddhi Dattatray Gorde     33
19        Mrunali Nilesh Kore     23
20  Mangesh Vijaykumar Ghodke     32
21              Amruta Gawade     33

In [16]:
df = pd.read_csv("pandas.csv")
print(df.shape)

(22, 7)

In [20]:
print(df['Marks'].max())
print(df['Marks'].min())

99
1

In [21]:
print(df['Marks'].mean())

42.86363636363637

In [22]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        22 non-null     str
 1   Age         21 non-null     float64
 2   Maths       22 non-null     int64
 3   Science     22 non-null     int64
 4   English     21 non-null     float64
 5   Computer    21 non-null     float64
 6   Percentage  20 non-null     float64
 7   Marks       22 non-null     int64
dtypes: float64(4), int64(3), str(1)
memory usage: 1.5 KB
None

In [23]:
data = {
    'Name':['Rahul','Priya',None],
    'Age':[22,None,23],
    'Marks':[80,90,None]
}

df = pd.DataFrame(data)

print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2   True  False   True

In [24]:
print(df.isnull().sum())

Name     1
Age      1
Marks    1
dtype: int64

In [25]:
print(df.isnull().any())

Name     True
Age      True
Marks    True
dtype: bool

In [28]:
df['Age'].fillna(df['Age'].mean())
print(df)

    Name   Age  Marks
0  Rahul  22.0   80.0
1  Priya   NaN   90.0
2    NaN  23.0    NaN

In [29]:
df['Marks'].fillna(0)
print(df)

    Name   Age  Marks
0  Rahul  22.0   80.0
1  Priya   NaN   90.0
2    NaN  23.0    NaN

In [33]:
df.dropna(inplace=True)
print(df)

    Name   Age  Marks
0  Rahul  22.0   80.0

# Product Dataframe

In [34]:
data = {
    'Product':['Laptop','Mobile','TV','Printer','Tablet'],
    'Category':['Electronics','Electronics','Electronics','Office','Electronics'],
    'Price':[50000,20000,30000,8000,15000],
    'Quantity':[5,10,3,8,12]
}

df = pd.DataFrame(data)
df

   Product     Category  Price  Quantity
0   Laptop  Electronics  50000         5
1   Mobile  Electronics  20000        10
2       TV  Electronics  30000         3
3  Printer       Office   8000         8
4   Tablet  Electronics  15000        12

In [37]:
(df[df['Category'] == 'Electronics'])

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1  Mobile  Electronics  20000        10
2      TV  Electronics  30000         3
4  Tablet  Electronics  15000        12

In [38]:
(df[df['Price'] > 10000])

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5
1  Mobile  Electronics  20000        10
2      TV  Electronics  30000         3
4  Tablet  Electronics  15000        12

In [39]:
(df['Price'].mean())

np.float64(24600.0)

In [40]:
(df[df['Price'] == df['Price'].max()])

  Product     Category  Price  Quantity
0  Laptop  Electronics  50000         5

In [44]:
(df[df['Price'] == df['Price'].min()])

   Product Category  Price  Quantity  Total_Price
3  Printer   Office   8000         8        64000

In [45]:
(df[df['Quantity'] > 7])

   Product     Category  Price  Quantity  Total_Price
1   Mobile  Electronics  20000        10       200000
3  Printer       Office   8000         8        64000
4   Tablet  Electronics  15000        12       180000

In [47]:
df['Total_Price'] = df['Price'] * df['Quantity']
(df)

   Product     Category  Price  Quantity  Total_Price
0   Laptop  Electronics  50000         5       250000
1   Mobile  Electronics  20000        10       200000
2       TV  Electronics  30000         3        90000
3  Printer       Office   8000         8        64000
4   Tablet  Electronics  15000        12       180000

In [48]:
(df[['Product','Total_Price']])

   Product  Total_Price
0   Laptop       250000
1   Mobile       200000
2       TV        90000
3  Printer        64000
4   Tablet       180000

In [49]:
(df['Quantity'].sum())

np.int64(38)